app/site/routes.py
import flask_login
from flask import Blueprint, render_template, url_for,redirect
from flask_wtf import FlaskForm, form
from flask_sqlalchemy import SQLAlchemy, query
from wtforms import StringField, PasswordField, SubmitField, BooleanField, IntegerField, HiddenField
from wtforms.validators import InputRequired, Length, ValidationError
from flask_bcrypt import Bcrypt, generate_password_hash, check_password_hash
from flask_login import logout_user, login_required, current_user, login_user

from app.api.routes import getrecipes, getuserrecipes
from app.extensions import db, logMan, bcrypt
from app.models import User, Recipe

site = Blueprint('site', __name__, template_folder='templates')

@site.route('/', methods=['GET'])
def index():
    return render_template('site/index.html')

@site.route('/login', methods=['GET', 'POST'])
def login():
    # return render_template('/empty.html')
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        print(user)
        print("submit")
        if user:
            print("if user")
            if check_password_hash(user.password, form.password.data):
                print("password correct")
                login_user(user)
                return redirect(url_for('site.home'))
    else:
        print("not authing")
        form = LoginForm()
        return render_template('site/login.html', form=form)

    return render_template('site/home.html', form=form, user=current_user)

@site.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        new_pass = bcrypt.generate_password_hash(form.password.data)
        new_user = User(username=form.username.data, password=new_pass)
        db.session.add(new_user)
        db.session.commit()
        form_1 = LoginForm()
        return render_template('site/login.html', form=form_1)
    return render_template('site/register.html', form=form)

@site.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    form = LoginForm()
    return render_template('site/login.html', form=form)

@site.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    reclist = getrecipes()
    print("this is getrec")
    print(reclist)
    return render_template('site/home.html', current_user=current_user, items=reclist)

@site.route('/profile', methods=['GET', 'POST', 'PUT'])
@login_required
def profile():
    getusrrec = getuserrecipes(current_user.username)
    return render_template('site/profile.html', current_user=current_user, items=getusrrec)

@site.route('/add_record', methods=['GET', 'POST'])
def add_record():
    form1 = AddRecord()
    if form1.validate_on_submit():
        name = form1.name
        serve = form1.serve
        prep = form1.prep
        cook = form1.cook
        ingr = form1.ingr
        instr = form1.instr
        time = form1.time
        author = form1.author
        record = Recipe(name=name.data, serve=serve.data, prep=prep.data, cook=cook.data, ingr=ingr.data, instr=instr.data, time=time.data, author=author.data)
        # Flask-SQLAlchemy magic adds record to database
        db.session.add(record)
        db.session.commit()
        # create a message to send to the template
        message = f"Recipe \"{name.data}\" for  {author.data} has been submitted."
        return render_template('site/add_record.html', message=message, form1=form1)
    else:
        return render_template('site/add_record.html', form1=form1)

class LoginForm(FlaskForm):
    username = StringField(validators=[InputRequired(), Length(min=4, max=20)], render_kw={"placeholder": "Username"})
    password = PasswordField(validators=[InputRequired(), Length(min=4, max=20)], render_kw={"placeholder": "Password"})
    submit = SubmitField('Login')
    remember = BooleanField('remember me')

class RegisterForm(FlaskForm):
    username = StringField(validators=[InputRequired(), Length(min=4, max=20)], render_kw={"placeholder": "Username"})
    password = PasswordField(validators=[InputRequired(), Length(min=8, max=20)], render_kw={"placeholder": "Password"})
    submit = SubmitField('Register')
    def validate_username(self, username):
        existing_user_username = User.query.filter_by(username=username.data).first()
        if existing_user_username:
            raise ValidationError('That username already exists. Please choose a different one.')

class AddRecord(FlaskForm):
    # id used only by update/edit
    id_field = HiddenField()
    name = StringField('Recipe name')
    serve = IntegerField('Servers')
    prep = StringField('Prep Time')
    cook = StringField('Cooking Time')
    ingr = StringField('Ingredients')
    instr = StringField('Instructions')
    time = StringField('Time to cook')
    author = StringField('Author (exact username)')
    # updated - date - handled in the route function
    updated = HiddenField()
    submit = SubmitField('Add Record')

app/site/templates/home.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='mystyle.css')}}">
<script src="{{url_for('static', filename='script.js')}}"></script>
{% endblock %}

{% block body %}
<body>
    <h1>The Recipe Bank!</h1>
    <h2>Hello {{user.name}}!</h2>

    <a href="{{ url_for('logout') }}">Logout</a><br>


</body>
{% endblock %}

app/site/templates/profile.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('.static', filename='mystyle.css')}}">
<script src="{{url_for('static', filename='script.js')}}"></script>
{% endblock %}

{% block body %}
<body>


<div>
  <h3>Your Recipe Bank</h3>
  <h2>Hello {{user.name}}!</h2>
  <table>
    <thead>
    <tr>
      <th>Recipe</th>
      <th>Serving Size</th>
      <th>Time</th>
    </tr>
    {% for r in recipes %}
    <tr>
      <td><a></a></td>
      <td></td>
      <td></td>
    </tr>
    {% endfor %}
  </table>

</div>

<br>
<button class="button"><a href="{{url_for('logout')}}">Logout</a></button>


</body>



{% endblock %}

app/site/templates/site/add_record.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
<!--<script src="{{url_for('static', filename='script.js')}}"></script>-->
{% endblock %}

{% block body %}
<body>


<div>
  <h3>Your Recipe Bank</h3>
  <h2>Hello {{current_user.username}}!</h2>
		{% if message %}

			<!-- the form was submitted and message exists -->
			<p class="lead"><strong>{{ message }}</strong></p>

			<!-- links -->
			<p><a href="{{ url_for('site.add_record') }}">Submit another recipe.</a></p>

			<p><a href="{{ url_for('site.home') }}">Return to the Home.</a></p>

		{% endif %}

		<form method="POST" action="/add_record">
        {{ form1.hidden_tag() }}
        Recipe Name: {{ (form1.name) }}
        <br>
        Serving size: {{ (form1.serve) }}
        <br>
        Prep Time: {{ (form1.prep) }}
		<br>
		Cooking Time: {{ (form1.cook) }}
        <br>
        Ingredients: {{ (form1.ingr) }}
        <br>
        Instructions: {{ (form1.instr) }}
		<br>
		Time to complete: {{ (form1.time) }}
		<br>
		Author: {{ (form1.author) }}
		<br>{{ (form1.submit) }}
    </form>


</div>

<br>
<button class="button"><a href="{{url_for('site.home')}}">Home</a></button>
<br>
<button class="button"><a href="{{ url_for('site.logout') }}">Logout</a></button>

</body>

{% endblock %}

app/site/templates/site/empty.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>CAN ANYONE HEAR ME</h1>
</body>
</html>

app/site/templates/site/home.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
<!--<script src="{{url_for('static', filename='script.js')}}"></script>-->
{% endblock %}

{% block body %}

<body>

    <h1>The Recipe Bank!</h1>
    <h2>Hello <a href="{{url_for('site.profile')}}">{{current_user.username}}!</a></h2>
    <button class="button"><a href="{{ url_for('site.logout') }}">Logout</a><br></button>
    <div>
        {% for items in items %}
        <div class="box">
            <h3>Name</h3>
            <p>{{ items.name }}</p>
            <br>
            <h3>Serves</h3>
            <p>{{ items.serve }}</p>
            <br>
            <h3>Prep Time</h3>
            <p>{{ items.prep }}</p>
            <br>
            <h3>Cook Time</h3>
            <p>{{ items.cook }}</p>
            <br>
            <h3>Ingredients</h3>
            <p>{{ items.ingr }}</p>
            <br>
            <h3>Instructions</h3>
            <p>{{ items.instr }}</p>
            <br>
            <h3>Time</h3>
            <p>{{ items.time }}</p>
            <br>
            <h3>Author</h3>
            <p>{{ items.author }}</p>
            <br>
        </div>
        {% endfor %}
    </div>



</body>

{% endblock %}

app/site/templates/site/index.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
<!--<script src="{{url_for('static', filename='script.js')}}"></script>-->
{% endblock %}

{% block body %}
<body>
    <h1>Welcome to The Recipe Bank!</h1>
    <a href="{{url_for('site.login')}}">Log in here!</a>
    <br>
    <a href="{{ url_for('site.register') }}">Don't have an account? Sign Up</a>

</body>
{% endblock %}

app/site/templates/site/login.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
<!--<script src="{{url_for('static', filename='script.js')}}"></script>-->
{% endblock %}

{% block body %}
<body>
    <h1>Welcome to The Recipe Bank!</h1>
    <form method="POST" action="/login">
        {{ form.hidden_tag() }}
        {{ (form.username) }}
        <br>
        {{ (form.password) }}
        <br>
        {{ (form.submit) }}
    </form>
    <br>
    <a href="{{ url_for('site.register') }}">Don't have an account? Sign Up</a>

</body>
{% endblock %}

app/site/templates/site/profile.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
<!--<script src="{{url_for('static', filename='script.js')}}"></script>-->
{% endblock %}

{% block body %}

<body>

    <h3>Your Recipe Bank</h3>
    <h2>Hello {{current_user.username}}!</h2>
    <button class="button"><a href="{{url_for('site.add_record')}}">ADD A RECORD!</a></button>
    <br>
    <button class="button"><a href="{{url_for('site.home')}}">Home</a></button>
    <br>
    <button class="button"><a href="{{ url_for('site.logout') }}">Logout</a></button>
    <br><hr>
        <div>
        {% for items in items %}
            <div class="box">
                <h3>Name</h3>
                <p>{{ items.name }}</p>
                <br>
                <h3>Serves</h3>
                <p>{{ items.serve }}</p>
                <br>
                <h3>Prep Time</h3>
                <p>{{ items.prep }}</p>
                <br>
                <h3>Cook Time</h3>
                <p>{{ items.cook }}</p>
                <br>
                <h3>Ingredients</h3>
                <p>{{ items.ingr }}</p>
                <br>
                <h3>Instructions</h3>
                <p>{{ items.instr }}</p>
                <br>
                <h3>Time</h3>
                <p>{{ items.time }}</p>
                <br>
                <h3>Author</h3>
                <p>{{ items.author }}</p>
                <br>
            </div>
            {% endfor %}




    </div>





</body>

{% endblock %}

app/site/templates/site/recipe.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/site/templates/site/register.html
{% extends 'bootstrap/base.html' %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
<!--<script src="{{url_for('static', filename='script.js')}}"></script>-->
{% endblock %}

{% block body %}
<body>
    <h1>Register Here</h1>
    <form method="POST" action="/register">
        {{ form.hidden_tag() }}
        {{ (form.username) }}
        <br>
        {{ (form.password) }}
        <br>
        {{ (form.submit) }}
    </form>
    <br>
    <a href="{{ url_for('site.login') }}">Already have an account? Log In</a>

</body>
{% endblock %}